#%RAML 1.0 DataType
type: object

properties:
  CarId?: integer
  CarCompany: string
  CarModel?: string
  CarNumber?: string
  CarType: string
  CarSeatingCapacity: integer
  FuleType?: string
  CarColor?: string
  Active: boolean
  CarDescription?: string