#%RAML 1.0 SecurityScheme
type: Basic Authentication
describedBy:
  headers:
    client-id:
      type: string
    client-secret:
      type: string
  responses:
    401: 
     description: Unauthorized or invalid client application credentials
    500:
      description: Bad request from authorized server