#%RAML 1.0 NamedExample
CarExample:
  CarId: 1
  CarCompany: "Skoda"
  CarModel?: "Octavia"
  CarNumber?: "A1 294"
  CarType: "SEDAN"
  CarSeatingCapacity: 5
  FuleType?: "Petrol"
  CarColor?: "Blue"
  Active: true
  CarDescription?: "Skoda Octavia 1.4 runs with petrol, and the fuel tank capacity of the car is up to 50 liters"